use super::ScopeGroup;

pub(super) const USER_TOKEN: ScopeGroup = ScopeGroup {
    name: "user-token",
    scopes: &["offline_access", "auth:user.id:read"],
};

pub(super) const CONTACT: ScopeGroup = ScopeGroup {
    name: "contact",
    scopes: &[
        "contact:contact.base:readonly",
        "contact:department.organize:readonly",
        "contact:contact:access_as_app",
        "contact:contact:readonly",
        "contact:contact:readonly_as_app",
    ],
};

pub(super) const DIRECTORY: ScopeGroup = ScopeGroup {
    name: "directory",
    scopes: &[
        "directory:employee:search",
        "directory:employee:read",
        "directory:employee:list",
        "directory:employee.base.base:read",
        "directory:employee.base.name.name:read",
        "directory:employee.base.name.another_name:read",
        "directory:employee.base.mobile:read",
        "directory:employee.base.email:read",
        "directory:employee.base.enterprise_email:read",
        "directory:employee.base.enterprise_email_alias:read",
        "directory:employee.base.avatar:read",
        "directory:employee.base.background_image:read",
        "directory:employee.base.description:read",
        "directory:employee.base.department:read",
        "directory:employee.base.department_path:read",
        "directory:employee.base.dept_order:read",
        "directory:employee.base.dotted_line_leaders:read",
        "directory:employee.base.external_id:read",
        "directory:employee.base.gender:read",
        "directory:employee.base.geo:read",
        "directory:employee.base.is_admin:read",
        "directory:employee.base.is_primary_admin:read",
        "directory:employee.base.is_resigned:read",
        "directory:employee.base.leader:read",
        "directory:employee.base.leader_id:read",
        "directory:employee.base.resign_time:read",
        "directory:employee.base.role:read",
        "directory:employee.base.status:read",
        "directory:employee.base.active_status:read",
        "directory:employee.base.subscription_ids:read",
        "directory:employee.base.custom_field:read",
        "directory:employee.base.data_source:read",
        "directory:employee.work.base_work:read",
        "directory:employee.work.employment:read",
        "directory:employee.work.employment_type:read",
        "directory:employee.work.extension_number:read",
        "directory:employee.work.job_number:read",
        "directory:employee.work.job_title:read",
        "directory:employee.work.join_date:read",
        "directory:employee.work.resign_date:read",
        "directory:employee.work.resign_reason:read",
        "directory:employee.work.resign_remark:read",
        "directory:employee.work.resign_type:read",
        "directory:employee.work.staff_status:read",
        "directory:employee.work.work_country_or_region:read",
        "directory:employee.work.work_place:read",
        "directory:employee.work.work_station:read",
        "directory:employee.work.job_level:read",
        "directory:employee.work.job_family:read",
        "directory:department.base:read",
        "directory:department.count:read",
        "directory:department.custom_field:read",
        "directory:department.data_source:read",
        "directory:department.department_path:read",
        "directory:department.external_id:read",
        "directory:department.has_child:read",
        "directory:department.leader:read",
        "directory:department.name:read",
        "directory:department.order_weight:read",
        "directory:department.organization:read",
        "directory:department.parent_id:read",
        "directory:department.status:read",
        "directory:job_title.base:read",
        "directory:job_title.status:read",
        "directory:job_family.base:read",
        "directory:job_family.path:read",
        "directory:job_family.status:read",
        "directory:job_level.base:read",
        "directory:job_level.order:read",
        "directory:job_level.status:read",
        "directory:place.base:read",
        "directory:place.status:read",
    ],
};

pub(super) const COREHR: ScopeGroup = ScopeGroup {
    name: "corehr",
    scopes: &[
        "corehr:corehr:readonly",
        "corehr:corehr",
        "corehr:department:read",
        "corehr:department:write",
        "corehr:department.manager:read",
        "corehr:department.organize:read",
        "corehr:department.custom_fields:read",
        "corehr:department.cost_center_id:read",
        "corehr:job.only:read",
        "corehr:job:read",
        "corehr:job:write",
        "corehr:job.job_level:read",
        "corehr:employee.job_data:read",
        "corehr:job_data:read",
        "corehr:job_data:write",
        "corehr:employment.job:read",
        "corehr:employment.job_level:read",
        "corehr:employment.job_level:write",
        "corehr:employment.pathway:read",
        "corehr:employment.pathway:write",
        "corehr:employment.position:read",
        "corehr:employment.position:write",
        "corehr:employment.job_grade:read",
        "corehr:employment.job_grade:write",
        "corehr:job_data.assignment_start_reason:read",
        "corehr:job_data.compensation_type:read",
        "corehr:job_data.job_data_reason:read",
        "corehr:job_data.service_company:read",
        "corehr:job_data.work_shift:read",
        "corehr:person:read",
        "corehr:person:write",
        "corehr:process:read",
        "contact:user.employee_id:readonly",
    ],
};

pub(super) const HIRE: ScopeGroup = ScopeGroup {
    name: "hire",
    scopes: &[
        "hire:talent:readonly",
        "hire:talent",
        "hire:people_cli",
        "hire:job:readonly",
        "hire:job.composite_info:readonly",
        "hire:job",
        "hire:application:readonly",
        "hire:application",
        "hire:interview:readonly",
        "hire:interview",
        "hire:job_process:readonly",
        "hire:job_requirement:readonly",
        "hire:job_requirement",
        "hire:attachment:readonly",
        "hire:attachment",
        "hire:location:readonly",
        "hire:subject:readonly",
        "hire:site:readonly",
        "hire:site",
        "hire:employee:readonly",
        "hire:evaluation:readonly",
        "hire:offer:readonly",
        "hire:offer_salary:readonly",
        "hire:agency:readonly",
        "hire:agency_salary:readonly",
        "hire:referral:readonly",
        "contact:user.employee_id:readonly",
    ],
};
