name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Format
        run: cargo fmt -- --check
      - name: Test
        run: cargo test --all-targets
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Package
        run: cargo package --allow-dirty
